dump:
    customer: dump/customer.pkl
    depot: dump/depot.pkl
    vendor: dump/vendor.pkl
flag:
    depot-customer: true
    gendata: true
    run_all: false
    vendor-depot: false
fname:
    correlation: input/correlation.json
    customer: input/market.json
    depot: input/depot.json
    item_type: data/items.csv
    time: input/time.json
    vehicle: input/vehicle_5.json
    vendor: input/vendor.json
gendata:
    gen_correlation:
        flag: true
        fname: D:\TaiLieuHocTap\DANO\benchmark_data\p22_correlation.csv
    gen_customer:
        flag: true
        fname: D:\TaiLieuHocTap\DANO\benchmark_data\p22_customer.csv
        high_thr: 140
        low_thr: 140
        n: -1
        out_fname: input/market.json
    gen_depot:
        flag: true
        fname: D:\TaiLieuHocTap\DANO\benchmark_data\p22_depot.csv
        high_thr: 11000
        low_thr: 10000
        n: -1
        out_fname: input/depot.json
    gen_vehicle:
        flag: true
        fname: null
        high_thr: 60
        low_thr: 60
        n: 5
    gen_vendor:
        flag: true
        fname: data/vendor.csv
        high_thr: 200000
        low_thr: 150000
        n: 10
        out_fname: input/vendor.json
other_config:
    coef list:
    - 1
    distance_type: euclidean
    no of items: 1
    no of items type: 1
    no of node threshold: 15
    no of vehicle types: 1
output:
    depot-customer:
        kmeans: output/depot-customer/KMeans_phase.json
        pre_tsp: output/depot-customer/pre_TSP_phase.json
        tsp: output/depot-customer/TSP_phase_with_Kmeans.json
    vendor-depot:
        kmeans: output/vendor-depot/KMeans_phase.json
        pre_tsp: output/vendor-depot/pre_TSP_phase.json
        tsp: output/vendor-depot/TSP_phase_with_Kmeans.json
